### ISSUE TITLE
Error in Windows 10

### ISSUE THREAD

**Issue by ethyde** [bitmade/node-twig#5]
Hi,

I try to use your package under Windows 10, but when i acces to my page, i have the following error : 

``Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "php I:\wamp\www\pmd-starterpack\node_modules\exec-php\lib\php\cli.php -pC:\Users\Ethyde\AppData\Local\Temp\tmp-5412vj0cn3k.tmp -rC:\Users\Ethyde\AppData\Local\Temp\tmp-5412bdmaq8g.tmp" ``

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)``

Can you help me ?
Thx.

**Comment by mamoschli** [comment]
Hi,
can you check if PHP is in your path? Kann you run PHP in the console by just typing `php -v` or something like that?

**Comment by ethyde** [comment]
Hi,

No problem with that : 
`$ php -v`
`PHP 5.6.25 (cli) (built: Aug 18 2016 11:39:15)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies`

**Comment by mamoschli** [comment]
Okay,
so that's not the problem :)

Could you please confirm that the Composer dependencies are installed correctly?
They should be in `node_modules/node-twig/php/vendor/...`.
I remember having an issue with downloading the files and executing Composer. If the vendor directory is not there this would be a quick fix for you since you most likely would have to install the dependencies by hand. (Running `composer install` inside the `node_modules/node-twig/php` folder should work. Or download `composer.phar` if you haven't got a global Composer).

**Comment by ethyde** [comment]
It's works ! 

Thanks for the quick fix :)

Do you plan to fix this ?

**Comment by mamoschli** [comment]
Hi,
I'm happy to help.

Of course I want to fix it, I have to speak to my colleague and try to remember what the issue was on his machine. I leave the issue open as a reminder :)

**Comment by mamoschli** [comment]
I just talked to my colleague and we remembered that the bug had something to do with PHP not being able to download the composer installer. This was due to some SSL related PHP problems. To check if this is the issue could you run the below code in your terminal and see if this works?

Both snippets are from the official Composer website. The first one is a little older and used by our package, the second is basically the code from https://getcomposer.org/download/ without checking the hash and deleting the downloaded file.

``` shell
php -r "readfile('https://getcomposer.org/installer');" | php
```

``` shell
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
```

If you get any errors executing the lines above we know it's more of a PHP issue.

**Comment by ethyde** [comment]
Hi,

Nothing special :)

![console](https://cloud.githubusercontent.com/assets/409987/20366747/c22a5082-ac4c-11e6-82e5-2f65e67417f3.jpg)

**Comment by mamoschli** [comment]
Hi there,
is the error still relevant?

If so, can you provide some information about your OS, PHP version and Node version?

**Comment by ethyde** [comment]
Hi, sorry for the delay, I migrate to MacOS for work, but i try to test it ASAP if it can help :)

**Comment by mamoschli** [comment]
Closing this due to inactivity
